# Generated by Django 4.2 on 2025-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='img',
            field=models.ImageField(default='defaault.jpg', upload_to='agent'),
        ),
    ]
